language: elixir

elixir:
  - 1.4.2

sudo: false

addons:
  postgresql: '9.4'

notifications:
  email: false

before_script:
  - |
    for app in $(ls apps);
    do
      cp apps/$app/config/travis_ci_test.exs apps/$app/config/test.secret.exs
    done
