language: elixir

elixir:
  - 1.4.2

sudo: false

addons:
  postgresql: '9.4'

notifications:
  email: false

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mix credo --strict
