language: elixir

elixir:
  - 1.4.2

sudo: false

addons:
  postgresql: '9.4'

notifications:
  email: false

before_script:
  - cp apps/sourcespace_web/config/travis_ci_test.exs apps/sourcespace_web/config/test.secret.exs
