language: elixir

elixir:
  - 1.4.2

sudo: false

addons:
  postgresql: '9.4'

notifications:
  email: false

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp apps/sourcespace_web/config/travis_ci_test.exs apps/sourcespace_web/config/test.secret.exs
  - cp apps/auth/config/travis_ci_test.exs apps/auth/config/test.secret.exs
